# Generated by Django 4.0 on 2022-01-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.FloatField(default=0.0)),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('cobrador', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='abonos.cobrador')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.FloatField(default=0.0)),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('concepto', models.CharField(blank=True, max_length=20)),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='abonos.cliente')),
                ('cobrador', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='abonos.cobrador')),
            ],
        ),
    ]
