# Generated by Django 4.0.1 on 2022-01-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0002_alter_abono_monto_alter_recaudacion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='concepto',
            field=models.CharField(blank=True, max_length=20, verbose_name='concepto'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='nota',
            field=models.CharField(blank=True, max_length=100, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=45, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cobrador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='cobrador',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='recaudacion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='recaudacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='recaudacion',
            name='nota',
            field=models.CharField(blank=True, max_length=100, verbose_name='nota'),
        ),
    ]
