# Generated by Django 4.0.1 on 2022-01-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0003_alter_abono_concepto_alter_abono_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='cliente',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='abonos.cliente'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='cobrador',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='abonos.cobrador'),
        ),
    ]
