# Generated by Django 4.0.1 on 2022-01-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0007_alter_recaudacion_cobrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonos.cliente'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='cobrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonos.cobrador'),
        ),
    ]
