# Generated by Django 4.0.1 on 2022-01-27 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abonos', '0008_alter_abono_cliente_alter_abono_cobrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrador',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
