# Generated by Django 4.0.1 on 2022-01-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0009_cobrador_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cobrador',
            options={'verbose_name': 'Cobrador', 'verbose_name_plural': 'Cobradores'},
        ),
        migrations.AlterModelOptions(
            name='recaudacion',
            options={'verbose_name': 'Recaudación', 'verbose_name_plural': 'Recaudaciones'},
        ),
    ]
