# Generated by Django 4.0.1 on 2022-01-29 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0010_alter_abono_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'ordering': ['modificado', 'creado'], 'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['modificado', 'creado'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cobrador',
            options={'ordering': ['modificado', 'creado'], 'verbose_name': 'Cobrador', 'verbose_name_plural': 'Cobradores'},
        ),
        migrations.AlterModelOptions(
            name='recaudacion',
            options={'ordering': ['modificado', 'creado'], 'verbose_name': 'Recaudación', 'verbose_name_plural': 'Recaudaciones'},
        ),
        migrations.AddField(
            model_name='abono',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abono',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recaudacion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recaudacion',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
