# Generated by Django 4.0.1 on 2022-01-31 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0011_alter_abono_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'ordering': ['-modificado', '-creado'], 'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-modificado', '-creado'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cobrador',
            options={'ordering': ['-modificado', '-creado'], 'verbose_name': 'Cobrador', 'verbose_name_plural': 'Cobradores'},
        ),
        migrations.AlterModelOptions(
            name='recaudacion',
            options={'ordering': ['-modificado', '-creado'], 'verbose_name': 'Recaudación', 'verbose_name_plural': 'Recaudaciones'},
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='recaudacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha'),
        ),
    ]
