# Generated by Django 4.0.1 on 2022-02-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0012_alter_abono_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='recaudacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonos.recaudacion'),
        ),
    ]
