# Generated by Django 4.0.1 on 2022-02-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0013_abono_recaudacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='recaudacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonos.recaudacion'),
        ),
    ]
