# Generated by Django 4.0.1 on 2022-02-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0014_alter_abono_recaudacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('apellido', 'nombre')},
        ),
    ]
